---
abstract: 'assert that code does not cause growth in memory usage'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::Builder::Tester: 0
  Test::More: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-MemoryGrowth
provides:
  Test::MemoryGrowth:
    file: lib/Test/MemoryGrowth.pm
    version: 0.02
recommends:
  Devel::MAT: 0.04
requires:
  Test::Builder: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
